//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsHomepageHelper {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NewsHomepageHelper.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;local:MyCard Margin=&quot;0,0,0,15&quot; Title=&quot; 的本地化字符串。
        /// </summary>
        internal static string Begin1 {
            get {
                return ResourceManager.GetString("Begin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  -  的本地化字符串。
        /// </summary>
        internal static string Begin2 {
            get {
                return ResourceManager.GetString("Begin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  &quot; CanSwap=&quot;True&quot; 的本地化字符串。
        /// </summary>
        internal static string Begin3 {
            get {
                return ResourceManager.GetString("Begin3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &gt;
        ///&lt;!--Header--&gt;
        ///&lt;StackPanel Margin=&quot;30,40,30,20&quot;&gt;
        ///&lt;Border Style=&quot;{StaticResource verImgBdr}&quot;&gt;
        ///&lt;Border.Background&gt;
        ///&lt;ImageBrush ImageSource=&quot; 的本地化字符串。
        /// </summary>
        internal static string Begin4 {
            get {
                return ResourceManager.GetString("Begin4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot; Stretch=&quot;Uniform&quot; /&gt;
        ///&lt;/Border.Background&gt;
        ///&lt;Image Source=&quot; 的本地化字符串。
        /// </summary>
        internal static string Begin5 {
            get {
                return ResourceManager.GetString("Begin5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot; Opacity=&quot;0&quot; /&gt;
        ///&lt;/Border&gt;
        ///&lt;Border Style=&quot;{StaticResource verTxtBdr}&quot;&gt;
        ///&lt;TextBlock Style=&quot;{StaticResource verTxtBlk}&quot; Text=&quot; 的本地化字符串。
        /// </summary>
        internal static string Begin6 {
            get {
                return ResourceManager.GetString("Begin6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot; /&gt;
        ///&lt;/Border&gt;
        ///&lt;!--Details--&gt; 的本地化字符串。
        /// </summary>
        internal static string BeginEnd {
            get {
                return ResourceManager.GetString("BeginEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;/StackPanel&gt;	
        ///&lt;/local:MyCard&gt; 的本地化字符串。
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot; Style=&quot;{StaticResource footnote}&quot; /&gt; 的本地化字符串。
        /// </summary>
        internal static string FootNoteEnd {
            get {
                return ResourceManager.GetString("FootNoteEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;TextBlock Text=&quot; 的本地化字符串。
        /// </summary>
        internal static string FootNoteStart {
            get {
                return ResourceManager.GetString("FootNoteStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://www.lightbeacon.top/pnh/newimgs/1_ 的本地化字符串。
        /// </summary>
        internal static string ImageLinkHead {
            get {
                return ResourceManager.GetString("ImageLinkHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;GroupBox Header=&quot;阅读完整日志&quot; BorderBrush=&quot;{DynamicResource ColorBrush3}&quot;&gt;
        ///&lt;Grid UseLayoutRounding=&quot;True&quot; Margin=&quot;10,10,10,10&quot;&gt;
        ///&lt;Grid.ColumnDefinitions&gt;
        ///&lt;ColumnDefinition Width=&quot;20*&quot;&gt;&lt;/ColumnDefinition&gt;
        ///&lt;ColumnDefinition Width=&quot;10*&quot;&gt;&lt;/ColumnDefinition&gt;
        ///&lt;ColumnDefinition Width=&quot;10*&quot;&gt;&lt;/ColumnDefinition&gt;
        ///&lt;/Grid.ColumnDefinitions&gt;
        ///&lt;local:MyButton Style=&quot;{StaticResource Read0}&quot; EventData=&quot; 的本地化字符串。
        /// </summary>
        internal static string Link1 {
            get {
                return ResourceManager.GetString("Link1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot; ColorType=&quot;Highlight&quot; /&gt;
        ///&lt;local:MyButton Style=&quot;{StaticResource Read1}&quot; EventData=&quot; 的本地化字符串。
        /// </summary>
        internal static string Link2 {
            get {
                return ResourceManager.GetString("Link2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;/&gt;
        ///&lt;local:MyButton Style=&quot;{StaticResource Read2}&quot; EventData=&quot; 的本地化字符串。
        /// </summary>
        internal static string Link3 {
            get {
                return ResourceManager.GetString("Link3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot; /&gt;
        ///&lt;/Grid&gt;
        ///&lt;/GroupBox&gt; 的本地化字符串。
        /// </summary>
        internal static string LinkEnd {
            get {
                return ResourceManager.GetString("LinkEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;/StackPanel&gt; 的本地化字符串。
        /// </summary>
        internal static string ListEnd {
            get {
                return ResourceManager.GetString("ListEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;/&gt; 的本地化字符串。
        /// </summary>
        internal static string ListItemEnd {
            get {
                return ResourceManager.GetString("ListItemEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Ellipse /&gt;
        ///&lt;TextBlock Style=&quot;{StaticResource ListItem}&quot; Text=&quot; 的本地化字符串。
        /// </summary>
        internal static string ListItemStart {
            get {
                return ResourceManager.GetString("ListItemStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;StackPanel Style=&quot;{StaticResource ListStyle}&quot;&gt; 的本地化字符串。
        /// </summary>
        internal static string ListStart {
            get {
                return ResourceManager.GetString("ListStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!--
        ///	 	              ___       ___                                                  
        ///     		         /\_ \    /&apos;___`\                                                
        ///       _____     ___\//\ \  /\_\ /\ \       ___      __   __  __  __    ____      
        ///     /\ &apos;__`\  /&apos;___\\ \ \ \/_/// /__     /&apos; _ `\  /&apos;__`\/\ \/\ \/\ \  /&apos;,__\     
        ///     \ \ \L\ \/\ \__/ \_\ \_  // /_\ \    /\ \/\ \/\  __/\ \ \_/ \_/ \/\__, `\    
        ///      \ \ ,__/\ \____\/\____\/\______/    \ \_\ \_\ \____\\ \___x___/&apos;\/\____/    
        ///       [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Mark {
            get {
                return ResourceManager.GetString("Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap MCWLogo {
            get {
                object obj = ResourceManager.GetObject("MCWLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Grid Margin=&quot;0,0,0,15&quot;&gt;
        ///&lt;Grid.ColumnDefinitions&gt;
        ///&lt;ColumnDefinition Width=&quot;1*&quot;&gt;&lt;/ColumnDefinition&gt;
        ///&lt;ColumnDefinition Width=&quot;100&quot;&gt;&lt;/ColumnDefinition&gt;
        ///&lt;ColumnDefinition Width=&quot;1*&quot;&gt;&lt;/ColumnDefinition&gt;
        ///&lt;/Grid.ColumnDefinitions&gt;
        ///&lt;Line X1=&quot;0&quot; X2=&quot;100&quot; Stroke=&quot;{DynamicResource ColorBrush5}&quot; StrokeThickness=&quot;1.5&quot; HorizontalAlignment=&quot;Center&quot; Stretch=&quot;Fill&quot; Grid.Column=&quot;0&quot; /&gt;
        ///&lt;TextBlock Text=&quot; 的本地化字符串。
        /// </summary>
        internal static string SeparatorBegin {
            get {
                return ResourceManager.GetString("SeparatorBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot; HorizontalAlignment=&quot;Center&quot; FontSize=&quot;14&quot; Foreground=&quot;{DynamicResource ColorBrush5}&quot; Grid.Column=&quot;1&quot; VerticalAlignment=&quot;Center&quot; /&gt;
        ///&lt;Line X1=&quot;0&quot; X2=&quot;100&quot; Stroke=&quot;{DynamicResource ColorBrush5}&quot; StrokeThickness=&quot;1.5&quot; HorizontalAlignment=&quot;Center&quot; Stretch=&quot;Fill&quot; Grid.Column=&quot;2&quot; /&gt;
        ///&lt;/Grid&gt; 的本地化字符串。
        /// </summary>
        internal static string SeparatorEnd {
            get {
                return ResourceManager.GetString("SeparatorEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;StackPanel xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot; xmlns:local=&quot;clr-namespace:PCL2&quot; &gt;&lt;StackPanel Margin=&quot;0,-10,0,0&quot;&gt;
        ///	&lt;!--Animations Starts--&gt;
        ///	&lt;StackPanel.Triggers&gt; 的本地化字符串。
        /// </summary>
        internal static string Stut1 {
            get {
                return ResourceManager.GetString("Stut1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;/StackPanel.Triggers&gt;
        ///	&lt;!--Animations Ends--&gt;
        ///
        ///	&lt;StackPanel.Resources&gt;
        ///		&lt;!--Template Starts--&gt;
        ///		&lt;!--Template Ends--&gt;
        ///		&lt;!--Styles Starts--&gt; 的本地化字符串。
        /// </summary>
        internal static string Stut2 {
            get {
                return ResourceManager.GetString("Stut2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;/StackPanel.Resources&gt; 的本地化字符串。
        /// </summary>
        internal static string Stut3 {
            get {
                return ResourceManager.GetString("Stut3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;/StackPanel&gt; 的本地化字符串。
        /// </summary>
        internal static string Stut4 {
            get {
                return ResourceManager.GetString("Stut4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;/StackPanel&gt; 的本地化字符串。
        /// </summary>
        internal static string StutEnd {
            get {
                return ResourceManager.GetString("StutEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;TextBlock Text=&quot; 的本地化字符串。
        /// </summary>
        internal static string Title1 {
            get {
                return ResourceManager.GetString("Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot; Style=&quot;{StaticResource h 的本地化字符串。
        /// </summary>
        internal static string Title2 {
            get {
                return ResourceManager.GetString("Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 }&quot; /&gt; 的本地化字符串。
        /// </summary>
        internal static string TitleEnd {
            get {
                return ResourceManager.GetString("TitleEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;local:MyButton EventType=&quot;打开网页&quot; EventData=&quot;https://minecraft.fandom.com/zh/wiki/ 的本地化字符串。
        /// </summary>
        internal static string WikiBtn1 {
            get {
                return ResourceManager.GetString("WikiBtn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;&gt;
        ///&lt;Border&gt;
        ///&lt;StackPanel&gt;
        ///&lt;Border Style=&quot;{StaticResource NameBdr}&quot;&gt;
        ///&lt;TextBlock Text=&quot; 的本地化字符串。
        /// </summary>
        internal static string WikiBtn2 {
            get {
                return ResourceManager.GetString("WikiBtn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot; /&gt;
        ///&lt;/Border&gt;
        ///&lt;Image Source=&quot; 的本地化字符串。
        /// </summary>
        internal static string WikiBtn3 {
            get {
                return ResourceManager.GetString("WikiBtn3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot; /&gt;
        ///&lt;/StackPanel&gt;
        ///&lt;/Border&gt;
        ///&lt;/local:MyButton&gt; 的本地化字符串。
        /// </summary>
        internal static string WikiBtnEnde {
            get {
                return ResourceManager.GetString("WikiBtnEnde", resourceCulture);
            }
        }
    }
}
